export const SKINS = [
  {
    id: "neon-night",
    name: "Neon Night",
    price: 0,
    desc: "Violet + vert, premium",
    animated: true,
    vars: {
      "--bg1": "#0b1020",
      "--bg2": "#0b1228",
      "--accent": "#7c3aed",
      "--accent2": "#22c55e",
      "--text": "#eaf0ff",
      "--muted": "rgba(234,240,255,.72)",
    },
  },
  {
    id: "ocean-glass",
    name: "Ocean Glass",
    price: 120,
    desc: "Bleu + cyan, calme",
    animated: true,
    vars: {
      "--bg1": "#071523",
      "--bg2": "#071a2b",
      "--accent": "#3b82f6",
      "--accent2": "#22d3ee",
      "--text": "#eaf6ff",
      "--muted": "rgba(234,246,255,.70)",
    },
  },
  {
    id: "sunset-luxe",
    name: "Sunset Luxe",
    price: 180,
    desc: "Rose + ambre, punchy",
    animated: true,
    vars: {
      "--bg1": "#1a0b1d",
      "--bg2": "#140a16",
      "--accent": "#ec4899",
      "--accent2": "#f59e0b",
      "--text": "#fff0fb",
      "--muted": "rgba(255,240,251,.70)",
    },
  },
  {
    id: "mint-minimal",
    name: "Mint Minimal",
    price: 150,
    desc: "Menthe, ultra clean",
    animated: false,
    vars: {
      "--bg1": "#071a16",
      "--bg2": "#04110f",
      "--accent": "#10b981",
      "--accent2": "#a7f3d0",
      "--text": "#eafff9",
      "--muted": "rgba(234,255,249,.70)",
    },
  },
  {
    id: "mono-premium",
    name: "Mono Premium",
    price: 220,
    desc: "Noir + argent, sobre",
    animated: false,
    vars: {
      "--bg1": "#090b10",
      "--bg2": "#06070b",
      "--accent": "#a3a3a3",
      "--accent2": "#ffffff",
      "--text": "#f5f7ff",
      "--muted": "rgba(245,247,255,.68)",
    },
  },
  {
    id: "candy-play",
    name: "Candy Play",
    price: 160,
    desc: "Ludique, colore",
    animated: true,
    vars: {
      "--bg1": "#0a0f25",
      "--bg2": "#070b1a",
      "--accent": "#a855f7",
      "--accent2": "#60a5fa",
      "--text": "#eef2ff",
      "--muted": "rgba(238,242,255,.72)",
    },
  },
  {
    id: "galaxy-animated",
    name: "Galaxy Animated",
    price: 1500,
    desc: "Ultra premium cosmÃ©tique",
    animated: true,
    premiumOnly: true,
    vars: {
      "--bg1": "#070916",
      "--bg2": "#090c24",
      "--accent": "#60a5fa",
      "--accent2": "#e879f9",
      "--text": "#f2f6ff",
      "--muted": "rgba(242,246,255,.72)",
    },
  },
  {
    id: "dark-gold",
    name: "Dark Gold",
    price: 1800,
    desc: "Noir + or, style elite",
    animated: true,
    premiumOnly: true,
    vars: {
      "--bg1": "#0d0b09",
      "--bg2": "#17120d",
      "--accent": "#f59e0b",
      "--accent2": "#fcd34d",
      "--text": "#fff6de",
      "--muted": "rgba(255,246,222,.72)",
    },
  },
  {
    id: "neon-cyber",
    name: "Neon Cyber",
    price: 1600,
    desc: "Cyberpunk lumineux",
    animated: true,
    premiumOnly: true,
    vars: {
      "--bg1": "#041019",
      "--bg2": "#031521",
      "--accent": "#06b6d4",
      "--accent2": "#22d3ee",
      "--text": "#e6fdff",
      "--muted": "rgba(230,253,255,.74)",
    },
  },
];

export const AVATARS = [
  { id: "owl", name: "Hibou", emoji: "🦉", price: 0, rarity: "Commun" },
  { id: "cat", name: "Chat", emoji: "🐱", price: 20, rarity: "Commun" },
  { id: "dog", name: "Chien", emoji: "🐶", price: 20, rarity: "Commun" },
  { id: "panda", name: "Panda", emoji: "🐼", price: 30, rarity: "Commun" },
  { id: "koala", name: "Koala", emoji: "🐨", price: 30, rarity: "Commun" },
  { id: "tiger", name: "Tigre", emoji: "🐯", price: 35, rarity: "Commun" },
  { id: "penguin", name: "Pingouin", emoji: "🐧", price: 35, rarity: "Commun" },
  { id: "frog", name: "Grenouille", emoji: "🐸", price: 25, rarity: "Commun" },
  { id: "unicorn", name: "Licorne", emoji: "🦄", price: 60, rarity: "Commun" },
  { id: "star", name: "Étoile", emoji: "⭐", price: 25, rarity: "Commun" },
  { id: "rocket", name: "Fusée", emoji: "🚀", price: 40, rarity: "Commun" },
  { id: "dice", name: "Dé", emoji: "🎲", price: 25, rarity: "Commun" },
  { id: "math", name: "Math", emoji: "🧮", price: 35, rarity: "Commun" },
  { id: "robot", name: "Robot", emoji: "🤖", price: 120, rarity: "Rare" },
  { id: "fox", name: "Renard", emoji: "🦊", price: 140, rarity: "Rare" },
  { id: "pirate", name: "Pirate", emoji: "🏴‍☠️", price: 140, rarity: "Rare" },
  { id: "astro", name: "Astronaute", emoji: "🧑‍🚀", price: 200, rarity: "Épique" },
  { id: "ninja", name: "Ninja", emoji: "🥷", price: 220, rarity: "Épique" },
  { id: "dragon", name: "Dragon", emoji: "🐉", price: 260, rarity: "Épique" },
  { id: "king", name: "Roi des Maths", emoji: "👑", price: 420, rarity: "Exclusif" },
  { id: "wizard", name: "Magicien", emoji: "🧙‍♂️", price: 520, rarity: "Exclusif" },
  { id: "genius", name: "Génie", emoji: "🧠", price: 650, rarity: "Exclusif" },
  { id: "mecha", name: "Mecha Calcul", emoji: "🦾", price: 780, rarity: "Exclusif" },
  { id: "phoenix-legend", name: "Phoenix", emoji: "🔥", price: 1400, rarity: "Légendaire", premiumOnly: true },
  { id: "void-master", name: "Void Master", emoji: "🌌", price: 1700, rarity: "Légendaire", premiumOnly: true },
];

export const ACHIEVEMENTS = [
  { id: "streak5", icon: "🔥", title: "Combo 5", desc: "Atteins un combo de 5.", reward: 50, type: "streak", target: 5 },
  { id: "streak10", icon: "🔥", title: "Combo 10", desc: "Atteins un combo de 10.", reward: 90, type: "streak", target: 10 },
  { id: "streak20", icon: "🔥", title: "Combo 20", desc: "Atteins un combo de 20.", reward: 160, type: "streak", target: 20 },
  { id: "right50", icon: "✅", title: "50 bonnes", desc: "Totalise 50 bonnes réponses.", reward: 80, type: "right", target: 50 },
  { id: "right100", icon: "✅", title: "100 bonnes", desc: "Totalise 100 bonnes réponses.", reward: 140, type: "right", target: 100 },
  { id: "right300", icon: "✅", title: "300 bonnes", desc: "Totalise 300 bonnes réponses.", reward: 260, type: "right", target: 300 },
  { id: "q100", icon: "🎯", title: "100 questions", desc: "Réponds à 100 questions.", reward: 90, type: "questions", target: 100 },
  { id: "q500", icon: "🎯", title: "500 questions", desc: "Réponds à 500 questions.", reward: 220, type: "questions", target: 500 },
  { id: "q1000", icon: "🎯", title: "1000 questions", desc: "Réponds à 1000 questions.", reward: 400, type: "questions", target: 1000 },
  { id: "acc90_50", icon: "🎖️", title: "Précision 90%", desc: "Atteins 90% de précision sur au moins 50 réponses.", reward: 200, type: "accuracy", target: 90 },
  { id: "rush250", icon: "⚡", title: "Rush 250", desc: "Atteins 250 points en mode Rush 60s.", reward: 220, type: "rush", target: 250 },
];

