export const SKINS = [
  {
    id: "ocean-kids",
    name: "Ocean Kids",
    price: 0,
    desc: "Ocean doux et lumineux",
    animated: true,
    vars: {
      "--bg1": "#0a1f3a",
      "--bg2": "#0f2d54",
      "--accent": "#35d5ff",
      "--accent2": "#8cf76a",
      "--text": "#f2fcff",
      "--muted": "rgba(242,252,255,.74)",
    },
  },
  {
    id: "candy-kids",
    name: "Candy Kids",
    price: 120,
    desc: "Bonbons, rose et sucre",
    animated: true,
    vars: {
      "--bg1": "#3a1f5f",
      "--bg2": "#5a2c86",
      "--accent": "#ff5ec9",
      "--accent2": "#ffd34f",
      "--text": "#fff4ff",
      "--muted": "rgba(255,244,255,.74)",
    },
  },
  {
    id: "space-kids",
    name: "Space Kids",
    price: 180,
    desc: "Espace magique et etoiles",
    animated: true,
    vars: {
      "--bg1": "#141a4f",
      "--bg2": "#1d2c6f",
      "--accent": "#6ed0ff",
      "--accent2": "#ff88f2",
      "--text": "#f6f7ff",
      "--muted": "rgba(246,247,255,.74)",
    },
  },
  {
    id: "jungle-kids",
    name: "Jungle Kids",
    price: 220,
    desc: "Jungle verte et fun",
    animated: true,
    vars: {
      "--bg1": "#0f2e2c",
      "--bg2": "#18453f",
      "--accent": "#60ef8f",
      "--accent2": "#ffee69",
      "--text": "#f4fff7",
      "--muted": "rgba(244,255,247,.74)",
    },
  },
  {
    id: "rainbow-kids",
    name: "Rainbow Kids",
    price: 320,
    desc: "Arc-en-ciel festival",
    animated: true,
    premiumOnly: true,
    vars: {
      "--bg1": "#2a1f63",
      "--bg2": "#3d2b8f",
      "--accent": "#4ef0ff",
      "--accent2": "#ff65cc",
      "--text": "#fdf8ff",
      "--muted": "rgba(253,248,255,.78)",
    },
  },
];

export const AVATARS = [
  { id: "owl", name: "Hibou", emoji: "🦉", price: 0, rarity: "Commun" },
  { id: "cat", name: "Chat", emoji: "🐱", price: 20, rarity: "Commun" },
  { id: "dog", name: "Chien", emoji: "🐶", price: 20, rarity: "Commun" },
  { id: "panda", name: "Panda", emoji: "🐼", price: 30, rarity: "Commun" },
  { id: "koala", name: "Koala", emoji: "🐨", price: 30, rarity: "Commun" },
  { id: "tiger", name: "Tigre", emoji: "🐯", price: 35, rarity: "Commun" },
  { id: "penguin", name: "Pingouin", emoji: "🐧", price: 35, rarity: "Commun" },
  { id: "frog", name: "Grenouille", emoji: "🐸", price: 25, rarity: "Commun" },
  { id: "unicorn", name: "Licorne", emoji: "🦄", price: 60, rarity: "Commun" },
  { id: "star", name: "Étoile", emoji: "⭐", price: 25, rarity: "Commun" },
  { id: "rocket", name: "Fusée", emoji: "🚀", price: 40, rarity: "Commun" },
  { id: "dice", name: "Dé", emoji: "🎲", price: 25, rarity: "Commun" },
  { id: "math", name: "Math", emoji: "🧮", price: 35, rarity: "Commun" },
  { id: "robot", name: "Robot", emoji: "🤖", price: 120, rarity: "Rare" },
  { id: "fox", name: "Renard", emoji: "🦊", price: 140, rarity: "Rare" },
  { id: "pirate", name: "Pirate", emoji: "🏴‍☠️", price: 140, rarity: "Rare" },
  { id: "astro", name: "Astronaute", emoji: "🧑‍🚀", price: 200, rarity: "Épique" },
  { id: "ninja", name: "Ninja", emoji: "🥷", price: 220, rarity: "Épique" },
  { id: "dragon", name: "Dragon", emoji: "🐉", price: 260, rarity: "Épique" },
  { id: "king", name: "Roi des Maths", emoji: "👑", price: 420, rarity: "Exclusif" },
  { id: "wizard", name: "Magicien", emoji: "🧙‍♂️", price: 520, rarity: "Exclusif" },
  { id: "genius", name: "Génie", emoji: "🧠", price: 650, rarity: "Exclusif" },
  { id: "mecha", name: "Mecha Calcul", emoji: "🦾", price: 780, rarity: "Exclusif" },
  { id: "phoenix-legend", name: "Phoenix", emoji: "🔥", price: 1400, rarity: "Légendaire", premiumOnly: true },
  { id: "void-master", name: "Void Master", emoji: "🌌", price: 1700, rarity: "Légendaire", premiumOnly: true },
];

export const ACHIEVEMENTS = [
  { id: "streak5", icon: "🔥", title: "Combo 5", desc: "Atteins un combo de 5.", reward: 50, type: "streak", target: 5 },
  { id: "streak10", icon: "🔥", title: "Combo 10", desc: "Atteins un combo de 10.", reward: 90, type: "streak", target: 10 },
  { id: "streak20", icon: "🔥", title: "Combo 20", desc: "Atteins un combo de 20.", reward: 160, type: "streak", target: 20 },
  { id: "right50", icon: "✅", title: "50 bonnes", desc: "Totalise 50 bonnes réponses.", reward: 80, type: "right", target: 50 },
  { id: "right100", icon: "✅", title: "100 bonnes", desc: "Totalise 100 bonnes réponses.", reward: 140, type: "right", target: 100 },
  { id: "right300", icon: "✅", title: "300 bonnes", desc: "Totalise 300 bonnes réponses.", reward: 260, type: "right", target: 300 },
  { id: "q100", icon: "🎯", title: "100 questions", desc: "Réponds à 100 questions.", reward: 90, type: "questions", target: 100 },
  { id: "q500", icon: "🎯", title: "500 questions", desc: "Réponds à 500 questions.", reward: 220, type: "questions", target: 500 },
  { id: "q1000", icon: "🎯", title: "1000 questions", desc: "Réponds à 1000 questions.", reward: 400, type: "questions", target: 1000 },
  { id: "acc90_50", icon: "🎖️", title: "Précision 90%", desc: "Atteins 90% de précision sur au moins 50 réponses.", reward: 200, type: "accuracy", target: 90 },
  { id: "rush250", icon: "⚡", title: "Rush 250", desc: "Atteins 250 points en mode Rush 60s.", reward: 220, type: "rush", target: 250 },
];
