export function buildMobileViewProps({
  activeMobilePage,
  navigateMobile,
  openArenaScreen,
  openShopPanel,
  openProfilePanel,
  openSettingsPanel,
  closeShopPanel,
  closeProfilePanel,
  closeSettingsPanel,
  installPromptEvent,
  isInstalledPwa,
  installPwaApp,
  startStudy5,
  openChest,
  worlds,
  selectedWorldId,
  onSelectWorld,
  ageBand,
  ageProfiles,
  onSelectAgeBand,
  kidModeOn,
  readAloudOn,
  shopTab,
  setShopTab,
  profileTab,
  setProfileTab,
  coins,
  SKINS,
  AVATARS,
  ownedSkins,
  skinId,
  canBuy,
  buySkin,
  equipSkin,
  ownedAvatars,
  avatarId,
  buyAvatar,
  equipAvatar,
  isPremium,
  cosmeticDust,
  authUser,
  level,
  loginStreak,
  totalRight,
  totalWrong,
  accuracy,
  totalQuestions,
  bestStreak,
  GRADES,
  DIFFS,
  MODES,
  records,
  unlockedCount,
  ACHIEVEMENTS,
  isUnlocked,
  achievements,
  answerEffects,
  ownedEffects,
  answerEffectId,
  unlockEffectWithDust,
  audioOn,
  setAudioOn,
  fxVolume,
  setFxVolume,
  vibrateOn,
  setVibrateOn,
  autoNextOn,
  setAutoNextOn,
  autoNextMs,
  setAutoNextMs,
  reduceMotion,
  setReduceMotion,
  skinAnimated,
  adaptiveOn,
  setAdaptiveOn,
  noPenaltyOnWrong,
  setNoPenaltyOnWrong,
  setKidModeOn,
  setReadAloudOn,
  pwCurrent,
  setPwCurrent,
  pwChangeNew,
  setPwChangeNew,
  pwChangeNew2,
  setPwChangeNew2,
  pwChangeMsg,
  changePasswordLoggedIn,
  avatar,
  profileRank,
  xpLabel,
  streak,
  currentWorld,
  worldLevel,
  worldProgress,
  worldBossReady,
  worldBossDone,
  chestPending,
  chestProgress,
  dailyChallenge,
  dailyProgress,
  study5LastSummary,
  onboardingDone,
}) {
  return {
    mobileHomeProps: {
      avatar,
      authUser,
      profileRank,
      coins,
      level,
      xp: xpLabel,
      streak,
      accuracy,
      loginStreak,
      currentWorld,
      worldLevel,
      worldProgress,
      worldBossReady,
      worldBossDone,
      chestPending,
      chestProgress,
      dailyChallenge,
      dailyProgress,
      worlds,
      selectedWorldId,
      onSelectWorld,
      ageBand,
      ageProfiles,
      onSelectAgeBand,
      kidModeOn,
      readAloudOn,
      canInstallApp: !isInstalledPwa && !!installPromptEvent,
      onInstallApp: installPwaApp,
      onOpenPlay: () => navigateMobile("classic-play"),
      onOpenArena: openArenaScreen,
      onOpenRush: () => navigateMobile("rush"),
      onOpenShop: openShopPanel,
      onOpenProfile: openProfilePanel,
      onOpenSettings: openSettingsPanel,
      onStartStudy5: startStudy5,
      onOpenChest: openChest,
    },
    mobileShopProps: {
      show: activeMobilePage === "shop",
      onClose: closeShopPanel,
      presentation: "page",
      shopTab,
      setShopTab,
      coins,
      SKINS,
      AVATARS,
      ownedSkins,
      skinId,
      canBuy,
      buySkin,
      equipSkin,
      ownedAvatars,
      avatarId,
      buyAvatar,
      equipAvatar,
      isPremium,
    },
    mobileProfileProps: {
      show: activeMobilePage === "profile",
      onClose: closeProfilePanel,
      presentation: "page",
      profileTab,
      setProfileTab,
      coins,
      cosmeticDust,
      authUser,
      level,
      loginStreak,
      totalRight,
      totalWrong,
      accuracy,
      totalQuestions,
      bestStreak,
      GRADES,
      DIFFS,
      MODES,
      records,
      unlockedCount,
      ACHIEVEMENTS,
      isUnlocked,
      achievements,
      SKINS,
      AVATARS,
      answerEffects,
      ownedSkins,
      ownedAvatars,
      ownedEffects,
      skinId,
      avatarId,
      answerEffectId,
      unlockEffectWithDust,
      ageBand,
      onboardingDone,
      study5LastSummary,
    },
    mobileSettingsProps: {
      show: activeMobilePage === "settings",
      onClose: closeSettingsPanel,
      presentation: "page",
      audioOn,
      setAudioOn,
      fxVolume,
      setFxVolume,
      vibrateOn,
      setVibrateOn,
      autoNextOn,
      setAutoNextOn,
      autoNextMs,
      setAutoNextMs,
      reduceMotion,
      setReduceMotion,
      skinAnimated,
      adaptiveOn,
      setAdaptiveOn,
      noPenaltyOnWrong,
      setNoPenaltyOnWrong,
      kidModeOn,
      setKidModeOn,
      readAloudOn,
      setReadAloudOn,
      pwCurrent,
      setPwCurrent,
      pwChangeNew,
      setPwChangeNew,
      pwChangeNew2,
      setPwChangeNew2,
      pwChangeMsg,
      changePasswordLoggedIn,
    },
  };
}
